"""
Ouverture des pôles méca et soft.

Le pôle est un ATTRIBUT des éléments d'un projet, pas un Hub séparé : les
trois pôles travaillent sur la même fusée. Les cartes existantes deviennent
donc « élec » (valeur par défaut du champ), et rien d'autre ne bouge.

Ajoute aussi les deux registres propres à ces pôles :
  MassItem — masse & centrage (méca) : la masse est la somme des pesées ;
  Flash    — version en place (soft) : c'est le dernier flash réussi.
"""

# Generated by Django 5.2.17 on 2026-08-18 11:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['project', 'pole', 'name']},
        ),
        migrations.AddField(
            model_name='board',
            name='pole',
            field=models.CharField(choices=[('elec', 'Élec'), ('meca', 'Méca'), ('soft', 'Soft')], default='elec', max_length=4, verbose_name='pôle'),
        ),
        migrations.AddField(
            model_name='project',
            name='cp_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Relevé dans OpenRocket — le Hub ne le calcule pas.', max_digits=8, null=True, verbose_name='centre de poussée (mm depuis la pointe)'),
        ),
        migrations.AddField(
            model_name='project',
            name='diameter_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='calibre (mm)'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text="Seuil de l'asso — vérifier le cahier des charges de la campagne en vigueur, il fait foi.", max_digits=4, verbose_name='marge statique minimale (calibres)'),
        ),
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('conception', 'Conception'), ('routage', 'Routage'), ('fabrication', 'Fabrication'), ('assemblage', 'Assemblage'), ('test', 'Test'), ('integration', 'Intégration'), ('vol', 'Vol'), ('resultat', 'Résultat'), ('cao', 'CAO'), ('developpement', 'Développement'), ('revue', 'Revue de code'), ('test_banc', 'Test au banc')], default='conception', max_length=15, verbose_name='étape'),
        ),
        migrations.AlterField(
            model_name='boardstage',
            name='stage',
            field=models.CharField(choices=[('conception', 'Conception'), ('routage', 'Routage'), ('fabrication', 'Fabrication'), ('assemblage', 'Assemblage'), ('test', 'Test'), ('integration', 'Intégration'), ('vol', 'Vol'), ('resultat', 'Résultat'), ('cao', 'CAO'), ('developpement', 'Développement'), ('revue', 'Revue de code'), ('test_banc', 'Test au banc')], max_length=15, verbose_name='étape'),
        ),
        migrations.AlterField(
            model_name='post',
            name='stage',
            field=models.CharField(blank=True, choices=[('conception', 'Conception'), ('routage', 'Routage'), ('fabrication', 'Fabrication'), ('assemblage', 'Assemblage'), ('test', 'Test'), ('integration', 'Intégration'), ('vol', 'Vol'), ('resultat', 'Résultat'), ('cao', 'CAO'), ('developpement', 'Développement'), ('revue', 'Revue de code'), ('test_banc', 'Test au banc')], max_length=15, verbose_name='étape'),
        ),
        migrations.CreateModel(
            name='Flash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40, verbose_name='version')),
                ('git_ref', models.CharField(blank=True, max_length=40, verbose_name='commit / tag')),
                ('ok', models.BooleanField(default=True, verbose_name='flash réussi')),
                ('author', models.CharField(max_length=60, verbose_name='par')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='contexte')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashes', to='hub.board')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashed_with', to='hub.board')),
            ],
            options={
                'verbose_name': 'flash',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='désignation')),
                ('mass_g', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='masse pesée (g)')),
                ('position_mm', models.DecimalField(decimal_places=1, help_text='Toujours depuis la POINTE : une origine commune, sinon le centrage est faux sans prévenir.', max_digits=8, verbose_name='position du CG de la pièce (mm depuis la pointe)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='précision')),
                ('author', models.CharField(max_length=60, verbose_name='pesée par')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mass_items', to='hub.board')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_items', to='hub.project')),
            ],
            options={
                'verbose_name': 'masse',
                'ordering': ['position_mm', 'id'],
            },
        ),
    ]
